TR-6 Negative Test Add Project
julsinkevich/TestRail_Test pull request #10
Opened 2021-11-06 20:11 UTC by julsinkevich

A negative test has been created, as well as a test for checking the default values. Fixed path to files in UI tests.

2021-11-08 07:27 UTC, mashadolya requested changes

2021-11-08 07:27 UTC, mashadolya commented on src/TestRail.API/Constants/ErrorMessage.cs
> +}
Pls pass `name` and `suite_mode` as parameters

2021-11-08 07:27 UTC, mashadolya commented on src/TestRail.API/Services/ProjectService.cs
> +        public Task<IRestResponse<ErrorResponse>> CreateProjectWrong(ProjectRequest projectRequest)
override would be better

2021-11-08 07:27 UTC, mashadolya commented on src/TestRail.API/Tests/CreateProjectNegativeTest.cs
> +            var howSuiteMode = ProjectFakerApi.GetProject();
rename `howSuiteMode`

2021-11-08 07:27 UTC, mashadolya commented on src/TestRail.API/Tests/CreateProjectNegativeTest.cs
> +        private static IEnumerable<object[]> NegativeProject()
I would suggest to create methods like `MissingProperties`, `IncorrectProperties` and `CorrectProperties`

2021-11-08 07:27 UTC, mashadolya commented on src/TestRail.API/Tests/CreateProjectNegativeTest.cs
> +        private static IEnumerable<object[]> NegativeProject()
And it would be better to move testCaseSources to the separate class

2021-11-08 07:27 UTC, mashadolya commented on src/TestRail.API/Tests/CreateProjectNegativeTest.cs
> +        public async Task CreateProject_withInvalidCredentials_ShouldBeBadRequest(ProjectRequest faker, string errorMessage)
ProjectRequest faker??

2021-11-08 07:27 UTC, mashadolya commented on src/TestRail.API/Tests/CreateProjectUseDefaultValues.cs
> +        public async Task CreateProject_withDefaultCredentials_ShouldBeOk(ProjectRequest faker)
withDefaultCredentials? Really ?)

2021-11-08 07:27 UTC, mashadolya commented on src/TestRail.API/Tests/CreateProjectUseDefaultValues.cs
> +                    response.Data.SuiteMode.Should().Be(3);
Hardcode

2021-11-08 07:27 UTC, mashadolya commented on src/TestRail.API/Tests/CreateProjectUseDefaultValues.cs
> +                response.StatusCode.Should().Be(HttpStatusCode.OK, "The status code should be OK");
We can create method for validation of response status code to avoid duplicates

2021-11-08 07:27 UTC, mashadolya commented on src/TestRail.API/Utils/RandomGenerator.cs
> +            var valueNotSuite = Enumerable.Range(-100, 100).Where(a => a < 1 || a > 3).ToArray();
https://qaevolution.ru/testovaya-dokumentaciya/test-dizajn/texnika-analiza-granichnyx-znachenij/

2021-11-08 07:59 UTC, julsinkevich commented on src/TestRail.API/Tests/CreateProjectNegativeTest.cs
> +            var howSuiteMode = ProjectFakerApi.GetProject();
incorrectSuiteMode

2021-11-08 08:13 UTC, julsinkevich commented on src/TestRail.API/Tests/CreateProjectNegativeTest.cs
> +        public async Task CreateProject_withInvalidCredentials_ShouldBeBadRequest(ProjectRequest faker, string errorMessage)
ProjectRequest fakerProject

2021-11-09 11:23 UTC, AlexanderHoha requested changes

2021-11-09 11:23 UTC, AlexanderHoha commented on src/TestRail.API/Tests/CreateProjectTest.cs
> +                response.StatusCode.Should().Be(HttpStatusCode.OK, StatusCode(HttpStatusCode.OK));
create custom assertion or add extension method to your model for verifying status code

2021-11-09 11:23 UTC, AlexanderHoha commented on src/TestRail.API/Tests/CreateProjectTest.cs
> +        public async Task CreateProject_UseAllProperties_ShouldBeSuccessful()
why we need to return something from test?

2021-11-09 11:23 UTC, AlexanderHoha commented on src/TestRail.API/Tests/CreateProjectTest.cs
> +        public async Task CreateProject_UseAllProperties_ShouldBeSuccessful()
What's the role of using await in test?

2021-11-09 11:23 UTC, AlexanderHoha commented on src/TestRail.API/Tests/CreatingProjectUseIncorrectCredentials.cs
> +            var user = new User();
maybe define invalid user as static field outside of the test

2021-11-09 11:23 UTC, AlexanderHoha commented on src/TestRail.API/DataSources/TestCaseSources.cs
> +                new object[]
returning array of objects? Why not to specify returning time like 
return new List<Project>

2021-11-09 11:23 UTC, AlexanderHoha commented on src/TestRail.API/Tests/CreateProjectUseDefaultValues.cs
> +            using (new AssertionScope())
if u are going to use same logic somewhere else consider making custom assertion for this

2021-11-09 11:55 UTC, mashadolya requested changes

2021-11-09 11:55 UTC, mashadolya commented on src/TestRail.API/Clients/RestClientExtended/RestClientExtended.cs
> +        }
duplicates

2021-11-09 11:55 UTC, mashadolya commented on src/TestRail.API/Constants/DefaultValues.cs
> +        public static string ProjectApiUrl => $"{TestSettings.BaseUrl}{Endpoints.HomePrefix.Replace("?", "\\?")}projects/overview/[0-9]+";
It should be in the folder related to model that has this default values in properties.

2021-11-09 11:55 UTC, mashadolya commented on src/TestRail.API/Constants/ErrorMessage.cs
> +        public static string NullValue(string nameValue) => $"Field :{nameValue} is a required field.";
Better naming like MissingRequiredValue

2021-11-09 11:55 UTC, mashadolya commented on src/TestRail.API/Constants/ErrorMessage.cs
> +        public static string IncorrectSuiteMode(string nameValue, int value) =>
`NotSupportedEnumValue`

2021-11-09 11:55 UTC, mashadolya commented on src/TestRail.API/Constants/ErrorMessage.cs
> +        public static string IncorrectShowAnnouncement(string nameValue) => $"Field :{nameValue} is not a valid boolean.";
`InvalidBoolean`

2021-11-09 11:55 UTC, mashadolya commented on src/TestRail.API/Constants/ErrorMessage.cs
> +        public static string IncorrectAnnouncement(string nameValue) => $"Field :{nameValue} is not a valid string.";
`InvalidString`

2021-11-09 11:55 UTC, mashadolya commented on src/TestRail.API/DataSources/TestCaseSources.cs
> +                new object[]
This solution is ok according to the Nunit docs

2021-11-09 11:55 UTC, mashadolya commented on src/TestRail.API/Fakers/ProjectFakerApi.cs
> +                .RuleFor(x => x.SuiteMode, f => 3)
Please avoid magic numbers

2021-11-09 11:55 UTC, mashadolya commented on src/TestRail.API/Fakers/ProjectFakerApi.cs
> +            return new Faker<IncorrectProjectResponse>()
it is request I guess

2021-11-09 11:55 UTC, mashadolya commented on src/TestRail.API/Services/ProjectService.cs
> +        public Task<IRestResponse<ErrorResponse>> CreateIncorrectProject(IncorrectProjectResponse projectRequest)
Can we use overload here?
Or I would suggest to create extension method like 

 ```
  public static ErrorsModel GetErrorsModel(this IRestResponse response)
        {
            return JsonConvert.DeserializeObject<ErrorsModel>(response.Content);
        }
```

2021-11-09 11:55 UTC, mashadolya commented on src/TestRail.API/Services/ProjectService.cs
> +        public Task<IRestResponse<ErrorResponse>> CreateIncorrectProject(IncorrectProjectResponse projectRequest)
By the way u can create extension for validation of status code

2021-11-09 11:55 UTC, mashadolya commented on src/TestRail.API/Tests/BaseTest.cs
> +        }
Not sure it is needed

2021-11-09 11:55 UTC, mashadolya commented on src/TestRail.API/Tests/CreateProjectIncorrectPropertiesNegativeTest.cs
> +            string errorMessage)
Formatting

2021-11-09 11:55 UTC, mashadolya commented on src/TestRail.API/Tests/CreateProjectMissingRequiredPropertiesNegativeTest.cs
> +    public class CreateProjectMissingRequiredPropertiesNegativeTest : BaseTest
We can create test class `CreateProjectNegativeTest` and store all tests here.
There is no need to create separate class for each test method

2021-11-09 11:55 UTC, mashadolya commented on src/TestRail.API/Tests/CreateProjectTest.cs
> +        public async Task CreateProject_UseAllProperties_ShouldBeSuccessful()
because async method should return Task, not void

2021-11-09 11:55 UTC, mashadolya commented on src/TestRail.API/Tests/CreateProjectMissingRequiredPropertiesNegativeTest.cs
> +        [Test(Description = "Creating a negative test project in TestRail using the API"),
It would be better to use description pattern like 
`
 [Test(Description = "POST /project incorrect location returns http status code 400")]`
 
 for all API tests

2021-11-09 11:55 UTC, mashadolya commented on src/TestRail.API/Tests/CreateProjectUseDefaultValues.cs
> +        }
I think it can be more beautiful 🧚🏻‍♂️

2021-11-09 11:55 UTC, mashadolya commented on src/TestRail.API/Tests/CreatingProjectUseIncorrectCredentials.cs
> +            _restClientExtended.BasicAuthorization(user);
Would be better just not to set authorization instead of passing null user....
Or do something like `_restClientExtended.Authorization = null`

2021-11-09 11:55 UTC, mashadolya commented on src/TestRail.API/Utils/RandomGenerator.cs
> +    public static class RandomGenerator
Seems like `RandomGenerator` is something common.
But here is `RandomInvalidSuiteMode`.....

2021-11-09 18:48 UTC, julsinkevich commented on src/TestRail.API/Services/ProjectService.cs
> +        public Task<IRestResponse<ErrorResponse>> CreateIncorrectProject(IncorrectProjectResponse projectRequest)
I decided to make the Create Project method universal using a generic and an object type parameter. This way I can perceive valid and invalid data. This reduces code and eliminates repetition.

2021-11-10 06:50 UTC, mashadolya requested changes

2021-11-10 06:50 UTC, mashadolya commented on src/TestRail.API/Services/ProjectService.cs
> +        public Task<IRestResponse<T>> CreateProject<T>(object projectRequest)
Can we use generic instead of object?

2021-11-10 06:50 UTC, mashadolya commented on src/TestRail.API/Tests/CreatingProjectIncorrectCredentials.cs
> +    public class CreatingProjectIncorrectCredentials
Here should be implementation of BaseTest

2021-11-10 06:50 UTC, mashadolya commented on src/TestRail.API/Utils/EnumAssertionsExtension.cs
> +        public static AndConstraint<EnumAssertions<HttpStatusCode>> StatusCodeBe(this EnumAssertions<HttpStatusCode> assert,
`StatusCodeShouldBe`

2021-11-10 06:50 UTC, mashadolya commented on src/TestRail.API/Utils/EnumAssertionsExtension.cs
> +                    because = "The status code should be OK";
Pls pass parameter `HttpStatusCode.OK` to the because string

2021-11-10 18:11 UTC, merged