tr-1: testing the page LogIn to TestRail
julsinkevich/TestRail_Test pull request #2
Opened 2021-09-27 20:12 UTC by julsinkevich

Test Case Link : https://app.qase.io/project/TR

2021-09-28 06:40 UTC, mashadolya requested changes
1. Please follow the C# code conventions 
2. Each commit message should start with capital letter
3. PR title should be `TR-1: E2e test login with valid credentials`

2021-09-28 06:40 UTC, mashadolya commented on src/Driver/DriverFactory.cs
> +        public static IWebDriver GetDriver(string name)
Unused variable name
If it is Factory it should return different types of drivers based f.e. on `name`

2021-09-28 06:40 UTC, mashadolya commented on src/Driver/DriverSingleton.cs
> +    public sealed class DriverSingleton
Why do we need singleton for driver object?

2021-09-28 06:40 UTC, mashadolya commented on src/Main.cs
> +    class Main
1. All classes, methods etc should have access modifiers
2. I would recommend to rename this class (f.e. BaseTest)

2021-09-28 06:40 UTC, mashadolya commented on src/Main.cs
> +        private IWebDriver _webDriver;
Should be blank line here
https://www.dofactory.com/csharp-coding-standards
https://docs.microsoft.com/ru-ru/dotnet/csharp/fundamentals/coding-style/coding-conventions

2021-09-28 06:40 UTC, mashadolya commented on src/Main.cs
> +            _webDriver.Close();
`Close` closes the the browser window on which the focus is set, but doesn’t  kill driver instance

2021-09-28 06:40 UTC, mashadolya commented on src/Models/LogInModels/ConfigurationModel.cs
> +    public class ConfigurationModel
It can be just `Configuration` without postfix 'Model'

2021-09-28 06:40 UTC, mashadolya commented on src/Pages/BasePage.cs
> +        }
Blank line

2021-09-28 06:40 UTC, mashadolya commented on src/Pages/BasePage.cs
> +        private readonly string _pageName;
Blank lines

2021-09-28 06:40 UTC, mashadolya commented on src/Pages/LogInPage.cs
> +        public LogInPage(IWebDriver webDriver) : base(webDriver, null, PagesNameResources.LogInPage)
Why page locator is null?
I would suggest to store page names in constants

2021-09-28 06:40 UTC, mashadolya commented on src/Resources/PagesNameResources.Designer.cs
> +﻿//------------------------------------------------------------------------------
Pls remove this strange thing

2021-09-28 06:40 UTC, mashadolya commented on src/Steps/LogInStep.cs
> +        public LogInStep LogIn(string username, string password)
Can we create model `User` instead of direct passing `username` and `password`?

2021-09-28 06:40 UTC, mashadolya commented on src/Tests/LogInTest.cs
> +            _webDriver.Url = _commonLogic.GetAppUrl();
Duplicates from `Main`

2021-09-28 06:40 UTC, mashadolya commented on src/Tests/LogInTest.cs
> +            _commonLogic = AppSettings.GetInstance();
Based on the name of this variable, it is not clear what is stored in it.

2021-09-28 06:40 UTC, mashadolya commented on src/Tests/LogInTest.cs
> +        public void LogIn()
Pls, use naming conventions for test methods
https://medium.com/@stefanovskyi/unit-test-naming-conventions-dd9208eadbea

2021-09-28 06:40 UTC, mashadolya commented on src/Utils/Waits.cs
> +        private const int timeOut = 10;
Better to store default timeout in config file

2021-09-28 06:40 UTC, mashadolya commented on src/Wrappers/WebElement.cs
> +                throw new Exception("Element does not exist", ex);
Maybe some information about this element?

2021-09-28 06:40 UTC, mashadolya commented on src/Wrappers/WebElement.cs
> +}
Do not commit commented/unused code

2021-09-28 06:40 UTC, mashadolya commented on src/appsettings.json
> +  "TestRail": {
Is it necessary to define object TestRail?

2021-09-28 09:46 UTC, julsinkevich commented on src/Driver/DriverFactory.cs
> +        public static IWebDriver GetDriver(string name)
Done. Returning different types of drivers by name.

2021-09-28 09:50 UTC, julsinkevich commented on src/Main.cs
> +    class Main
Done. This class has modifiers as 'internal'. Renamed this class as 'Base Test'

2021-09-28 09:51 UTC, julsinkevich commented on src/appsettings.json
> +  "TestRail": {
Done. Changed json.

2021-09-28 10:03 UTC, julsinkevich commented on src/Main.cs
> +        private IWebDriver _webDriver;
Done. Added blank line. Read these articles.

2021-09-28 10:09 UTC, julsinkevich commented on src/Main.cs
> +            _webDriver.Close();
Done. I have used method ''Disposes()".

2021-09-28 10:56 UTC, julsinkevich commented on src/Tests/LogInTest.cs
> +        public void LogIn()
Done. Renamed to "LogIn_withValidCredentials_ShouldBeSuccessful"

2021-09-28 11:48 UTC, julsinkevich commented on src/Wrappers/WebElement.cs
> +}
Done

2021-09-28 11:55 UTC, julsinkevich commented on src/Driver/DriverSingleton.cs
> +    public sealed class DriverSingleton
I developed a class in such a way that it can have only instance at any time(Singleton  pattern). When me need to use same object of a class across all future tests. Singleton class must return the same instance again, if it is instantiated again.

2021-09-28 11:56 UTC, julsinkevich commented on src/Utils/Waits.cs
> +        private const int timeOut = 10;
During the fix, I discovered that I was not using this class, so I removed it.

2021-09-28 12:44 UTC, julsinkevich commented on src/Wrappers/WebElement.cs
> +                throw new Exception("Element does not exist", ex);
Done

2021-09-28 12:56 UTC, mashadolya requested changes

2021-09-28 12:56 UTC, mashadolya commented on src/Capabilities/DriverCapabilityGenerator.cs
> +        public static FirefoxOptions GetFireFoxOptions()
Blank line

2021-09-28 12:56 UTC, mashadolya commented on src/Driver/DriverSingleton.cs
> +    public sealed class DriverSingleton
Delete single ton

2021-09-28 12:56 UTC, mashadolya commented on src/Utils/AppSettings.cs
> +    }
delete it

2021-09-28 12:56 UTC, mashadolya commented on src/Wrappers/WebElement.cs
> +                throw new Exception($"Element {locator} does not exist", ex);
pass name as parameter

2021-09-28 20:09 UTC, mashadolya requested changes

2021-09-28 20:09 UTC, mashadolya commented on src/Utils/AppSettings.cs
> +        public int DefaultTimeOut => _root.ElementExistenseWaitTimeOut;
In case of a large number of config properties this solution is not the best one

2021-09-28 20:09 UTC, mashadolya commented on src/Pages/LogInPage.cs
> +            new Wrappers.WebElement("UsernameInput", Driver, EmailSelector).SendKeys(username);
new Wrappers? 🙄

2021-09-28 20:09 UTC, mashadolya commented on src/Utils/Waits.cs
> +        public static bool IsElementVisible(IWebDriver webDriver, By locator)
Let's pass time out as parameter here
This way you will be able to define another timeout value for specific elements which, for example, usually take longer to load than others

2021-09-28 20:09 UTC, mashadolya commented on src/Wrappers/WebElement.cs
> +        private IWebElement _element;
Code conventions 😡

2021-09-28 20:09 UTC, mashadolya commented on src/Wrappers/WebElement.cs
> +        public WebElement(string name, IWebDriver webDriver, By locator)
Unused name?

2021-09-28 20:09 UTC, mashadolya commented on src/Wrappers/WebElement.cs
> +                throw new Exception($"Element {_element} with {locator} does not exist", ex);
Do u really need IWebelement object to be logged?

2021-09-29 12:04 UTC, mashadolya requested changes

2021-09-29 12:04 UTC, mashadolya commented on src/Pages/BasePage.cs
> +            var appSettings = new AppSettings();
Use appsettings from base test (make it static public)

2021-09-29 12:04 UTC, mashadolya commented on src/Steps/LogInStep.cs
> +        public LogInStep LogIn(string username, string password)
Still Haven't implemented

2021-09-29 12:04 UTC, mashadolya commented on src/Utils/Waits.cs
> +        public static bool IsElementVisible(IWebDriver webDriver, By locator, int defaultTimeOut)
` public static bool IsElementVisible(IWebDriver webDriver, By locator, int defaultTimeOut = Appsettings.DefaultTimeOut)`

2021-09-29 19:00 UTC, mashadolya requested changes

2021-09-29 19:00 UTC, mashadolya commented on src/Utils/AppSettings.cs
> +        public static User User => GetRootSettings().Users.FirstOrDefault();
BLANK LINE!!!!!!!!!!!!!!!!

2021-09-29 19:00 UTC, mashadolya commented on src/Utils/AppSettings.cs
> +        public static User User => GetRootSettings().Users.FirstOrDefault();
What if there will be needed the second user? The third ??

2021-09-29 19:00 UTC, mashadolya commented on src/Wrappers/WebElement.cs
> +                return _element;
can be just  `_return _webDriver.FindElement(locator);`

2021-09-29 19:00 UTC, mashadolya commented on src/appsettings.json
> +  ]
Should be one driver

2021-09-30 09:30 UTC, mashadolya approved these changes

2021-09-30 09:30 UTC, merged